# Generated by Django 4.0.2 on 2023-01-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_curso_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('monotributista', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='inscriptos',
            field=models.IntegerField(verbose_name='Inscriptos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], null=True, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.profesor'),
        ),
    ]
